apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observability
  namespace: aws-otel-eks
spec:
  mode: deployment
  serviceAccount: aws-otel-collector
  env:
    - name: CLUSTER_NAME
      value: eks-blueprint
  ports:
    - name: otel-grpc
      port: 4317
      protocol: TCP
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50

    exporters:
      awsxray:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [awsxray]